### ISSUE TITLE
Ability to request markdown format from command line

### ISSUE THREAD

**Issue by strawp** [bwilczynski/strava-cli#18]
Hi, love this project!

As the tables use tabulate can the enumerable at https://github.com/bwilczynski/strava-cli/blob/master/strava/decorators.py#L20 be extended to support "github" and have this able to be specified through a command line switch?

Thanks!

**Comment by bwilczynski** [comment]
Hi, good to hear that. This sounds like a great addition - do you think you would be able to implement it and open a PR?

**Comment by strawp** [comment]
Sure, OK!

I'll try not to mess up your nice neat code ;)
