### ISSUE TITLE
Create an app

### ISSUE THREAD

**Issue by vibrog** [bwilczynski/strava-cli#8]
Wouldn't it be a good idea to create an application at Strava that are used by everyone?
Simplifies setup.

**Comment by bwilczynski** [comment]
It would also mean leaking secret key to anyone that can read the code and would allow malicious code to access Strava API impersonating the CLI tool. When Strava exposes authentication method using OAuth2 Authorization Code with PKCE Flow your suggestion would be possible to implement.
